config/routes.rb
Rails.application.routes.draw do
  resources :rappers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "rappers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rapper.rb
class Rapper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rappers_controller.rb
class RappersController < ApplicationController
  before_action :set_rapper, only: %i[ show edit update destroy ]

  # GET /rappers or /rappers.json
  def index
    @rappers = Rapper.all
  end

  # GET /rappers/1 or /rappers/1.json
  def show
  end

  # GET /rappers/new
  def new
    @rapper = Rapper.new
  end

  # GET /rappers/1/edit
  def edit
  end

  # POST /rappers or /rappers.json
  def create
    @rapper = Rapper.new(rapper_params)

    respond_to do |format|
      if @rapper.save
        format.html { redirect_to rapper_url(@rapper), notice: "Rapper was successfully created." }
        format.json { render :show, status: :created, location: @rapper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rappers/1 or /rappers/1.json
  def update
    respond_to do |format|
      if @rapper.update(rapper_params)
        format.html { redirect_to rapper_url(@rapper), notice: "Rapper was successfully updated." }
        format.json { render :show, status: :ok, location: @rapper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rappers/1 or /rappers/1.json
  def destroy
    @rapper.destroy!

    respond_to do |format|
      format.html { redirect_to rappers_url, notice: "Rapper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rapper
      @rapper = Rapper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rapper_params
      params.require(:rapper).permit(:image, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rappers_helper.rb
module RappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rap Guez</title>
    <link rel="icon" href="../../assets/images/logo rap guez.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rappers/_form.html.erb
<%= form_with(model: rapper) do |form| %>
  <% if rapper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rapper.errors.count, "error") %> prohibited this rapper from being saved:</h2>

      <ul>
        <% rapper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rappers/_rapper.html.erb
<div id="<%= dom_id rapper %>">
  <p>
    <strong>Image:</strong>
    <%= rapper.image %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= rapper.name %>
  </p>

</div>

app/views/rappers/edit.html.erb
<h1>Editing rapper</h1>

<%= render "form", rapper: @rapper %>

<br>

<div>
  <%= link_to "Show this rapper", @rapper %> |
  <%= link_to "Back to rappers", rappers_path %>
</div>

app/views/rappers/index.html.erb
<h1>Rap<span>Guez</span></h1>
<section class="hero">
  <h2>Nos rappeurs</h2>
    <%= link_to "Ajouter un rappeur ?", new_rapper_path %>
</section>


<section class="grid">
  <% @rappers.each do |rapper| %>
    <div class="rapper">
        <%= image_tag(rapper.image) %>
        <p>
          <%= rapper.name%>
        </p>
    </div>
  <% end %>
</section>

app/views/rappers/new.html.erb
<h1>New rapper</h1>

<%= render "form", rapper: @rapper %>

<br>

<div>
  <%= link_to "Back to rappers", rappers_path %>
</div>

app/views/rappers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rapper %>

<div>
  <%= link_to "Edit this rapper", edit_rapper_path(@rapper) %> |
  <%= link_to "Back to rappers", rappers_path %>

  <%= button_to "Destroy this rapper", @rapper, method: :delete %>
</div>